#!/bin/bash
# Tauri 应用开启开发者工具的方法

echo "========================================="
echo "Tauri 应用开发者工具查看方法："
echo "========================================="
echo ""
echo "方法1: 应用内快捷键"
echo "  - macOS: Cmd + Option + I"
echo "  - Windows/Linux: Ctrl + Shift + I"
echo ""
echo "方法2: 终端查看日志"
echo "  在终端运行应用时，console.log 会直接输出到终端"
echo "  命令: npm run tauri dev"
echo ""
echo "方法3: 如果是打包后的 .app"
echo "  可以在终端启动应用查看日志:"
echo "  ./大香蕉\ AI.app/Contents/MacOS/desktop"
echo ""
echo "========================================="
